let routeData = [
    {
        title:'订单管理',
        children:[
            {
                title:'贷款订单',
                path:'/home/order/dk'
            },
            {
                title:'转单订单',
                path:'/home/order/zd'
            },
            {
                title:'保险订单',
                path:'/home/order/bx'
            }
        ]
    },
    {
        title:'财务管理',
        children:[
            {
                title:'贷款管理',
                path:'/home'
            },
            {
                title:'转单管理',
                path:'/home'
            },
            {
                title:'保险管理',
                path:'/home'
            }
        ]
    }
]
export default routeData;